version: "3.3"
services:
  app:
    container_name: watchers_app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
    restart: always
