version: "3.3"
services:
  app:
    container_name: watchers_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - database
  database:
    container_name: watchers_database
    image: mongo:3.4.10
    command: mongod --dbpath /data/db
    volumes:
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
